version: '3.6'

services:

  uschedule.api:
    image: uschedule/uschedule.api:${TAG:-latest}
    build:
      context: src
      dockerfile: USchedule.API/Dockerfile    
    environment:
      - ASPNETCORE_ENVIRONMENT="DEVELOPMENT"
      - ASPNETCORE_URLS=http://*:5000
      - DbProvider=Postgres
      - DbConnection=Server=database;Database=uschedule;User Id=uschedule;Password=uschedule
    ports:
      - "5000:5000"
    links:
      - "db:database"
  db: 
    image: postgres
    environment:
      - POSTGRES_USER=uschedule
      - POSTGRES_PASSWORD=uschedule     
    expose:
      - "5432"
    ports:
      - "5432:5432"

  parser:
    image: uschedule/uschedule.parser:${TAG:-latest}
    build:
      context: src
      dockerfile: USchedule.Parser/Dockerfile
    links:
      - "uschedule.api:uscheduleapi"
    tty: true
    